name: PR Checks
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  'Checking':
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
      - name: '        Tests'
        run: npm cit
      - name: '     Coverage'
        if: success()
        uses: actions/upload-artifact@v1.0.0
        with:
          name: 'COVERAGE'
          path: 'coverage/'
      - name: '      CodeCov'
        if: success()
        uses: codecov/codecov-action@v1.0.10
        with:
          file: 'COVERAGE*'
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false
