name: PR/PUSH Checks
on: [push,pull_request]
jobs:
  Checking:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
      - name: 'Setup...'
        run: npm ci --no-optional
      - name: 'JS   Standard'
        if: success()
        run: npm run lint:standard
      - name: 'JS     ESLint'
        if: success()
        run: npm run lint
      - name: 'CSS Stylelint'
        if: success()
        run: npm run lint:css
      - name: '        Tests'
        if: success()
        run: npm test
      - name: '     Coverage'
        if: success()
        uses: actions/upload-artifact@v1.0.0
        with:
          name: 'Coverage'
          path: 'coverage/'
      - name: '      Codecov'
        if: success()
        uses: codecov/codecov-action@v1.0.5
        with:
          file: 'coverage/*'
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false
      - name: 'Tag PreRelease'
        if: success()
        uses: mathieudutour/github-tag-action@v3
        with:
          github_token: ${{ secrets.TTL_RELEASE_TOKEN }}
          default_bump: patch
          tag_prefix: v.
          release_branches: v.*
    env:
        CI: true
