name: MacOS
on:
  push:
    branches:
    - staging
    tags:
    - v.*
jobs:
  Packaging:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
    - name: Building App
      run: |
        npm ci --no-optional
        npm run package:mac
    - name: Uploading App
      uses: actions/upload-artifact@v1.0.0
      with:
        name: 'Time to Leave.app'
        path: 'release-builds/Time to Leave-darwin-x64/Time to Leave.app'
    - name: Creating DMG Package
      run: npx electron-installer-dmg 'release-builds/Time to Leave-darwin-x64/Time to Leave.app/' time-to-leave --out 'release-dmg' --icon=assets/icon-mac.icns
    - name: Uploading DMG Package
      uses: actions/upload-artifact@v1.0.0
      with:
        name: 'Time to Leave.dmg'
        path: 'release-dmg/'
      env:
        CI: true
