name: Node CI

on: [push]

jobs:
  build:
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
        runs-on: [ubuntu-latest, windows-latest]
        
    runs-on: ${{ matrix.runs-on }}        
    
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        export DISPLAY=:99.0
        Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
        npm install
        npm run build --if-present
        npm test
      env:
        CI: true
    - name: lint
      run: |
        npm install
        npm run lint
      env:
        CI: true
