name: 'Prepare Release'
on:
  push:
    branches:
      - ci*
    tags:
      - v.*
      - latest*

jobs:

  'MacOS':
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
    - name: 'Building...'
      run: |
        npm ci
        npm run package:mac
