name: 'Release'
on: 
  push:
    branches:
    - master
    - v.*
jobs:
  'MacOS':
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
    - name: 'Building...'
      run: |
        npm ci --no-optional
        npm run package:mac
    - name: 'Building DMG Package...'
      run: npx electron-installer-dmg 'release-builds/Time to Leave-darwin-x64/Time to Leave.app/' time-to-leave --out 'release-dmg' --icon=assets/icon-mac.icns
    - name: 'Uploading...'
      uses: actions/upload-artifact@v1.0.0
      with:
        name: 'Time to Leave - OSX'
        path: 'release-dmg/time-to-leave.dmg'
    - name: 'Creating Pre-Release...'
      uses: marvinpinto/action-automatic-releases@v0.2.2
      with:
        repo_token: ${{ secrets.TTL_RELEASE_TOKEN }}
        draft: true
        prerelease: true
        title: 'Time to Leave - MacOS'
        files: 'release-dmg/time-to-leave.dmg'

  'Ubuntu_Debian':
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
      - name: 'Building...'
        run: |
          npm ci --no-optional
          npm run package:deb
      - name: 'Creating Debian Package'
        run: npx electron-installer-debian --src 'release-builds/time-to-leave-linux-x64/' --dest 'release-deb/' --arch amd64
      - name: 'Uploading...'
        uses: Shopify/upload-to-release@1.0.0
        with:
          name: 'Time to Leave - Debian' 
          path: 'release-deb/'
          repo-token: ${{ secrets.TTL_RELEASE_TOKEN }}

  'Windows':
      runs-on: windows-latest
      steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
      - name: 'Building ASAR...'
        run: |
          npm ci --no-optional
          npm run package:win -- --asar
      - name: 'Uploading ASAR Package'
        uses: actions/upload-artifact@v1.0.0
        with:
          name: 'Time to Leave - Windows (Exe)'
          path: 'release-builds\Time to Leave-win32-ia32\Time to Leave.exe'
      - name: 'Creating Installer...'
        run: |
          npm run package:win-squirrel
          npx electron-installer-windows --src 'release-builds/time-to-leave-win32-ia32' --dest 'squirrel-release'
      - name: 'Uploading Installer...'
        uses: actions/upload-artifact@v1.0.0
        with:
          name: 'Time to Leave - Windows'
          path: 'squirrel-release/time_to_leave-1.3.0-setup.exe'
      - name: 'Creating Pre-Release...'
        uses: marvinpinto/action-automatic-releases@v0.2.2
        with:
          repo_token: ${{ secrets.TTL_RELEASE_TOKEN }}
          draft: true
          prerelease: true
          title: 'Time to Leave - Windows'
          files: 'squirrel-release/time_to_leave-1.3.0-setup.exe'

env:
  CI: true
