name: 'Prepare Release'
on:
  push:
    tags:
    - v.*
jobs:

  'MacOS':
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
    - name: 'Building...'
      run: |
        npm ci --no-optional
        npm run package:mac
        
    - name: 'Uploading App to Artifacts'
      if: success()
      uses: actions/upload-artifact@v1.0.0
      with:
        name: 'Time-to-Leave.app'
        path: './release-builds/Time to Leave-darwin-x64/Time to Leave.app'

    - name: 'Packing DMG...'
      if: success()
      run: npx electron-installer-dmg './release-builds/Time to Leave-darwin-x64/Time to Leave.app/' time-to-leave --out 'release-dmg/' --icon=assets/icon-mac.icns --verbose

    - name: 'Upload DMG to Artifacts'
      if: success()
      uses: actions/upload-artifact@v1.0.0
      with:
        name: 'Time-to-Leave.dmg'
        path: 'release-dmg/time-to-leave.dmg'

    - name: 'GH Release'
      if: success()
      uses: softprops/action-gh-release@v0.1.5
      with:
        draft: true
        prerelease: true
        files: 'releases-dmg/**'

  'Debian':
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
      - name: 'Building...'
        run: |
          npm ci --no-optional
          npm run package:deb
          
      - name: 'Packing DEB'
        if: success()
        run: |
          npx electron-installer-debian --src 'release-builds/time-to-leave-linux-x64/' --dest 'release-deb/' --arch amd64 --verbose
          ls release-deb/
      - name: 'Upload DEB to Artifacts'
        if: success()
        uses: actions/upload-artifact@v1.0.0
        with:
          name: 'time-to-leave.deb'
          path: 'release-deb/time-to-leave_1.4.0~beta.2_amd64.deb'
        
  'Windows':
      runs-on: windows-latest
      steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
      - name: 'Building ASAR...'
        run: |
          npm ci --no-optional
          npm run package:win -- --asar
      - name: 'Uploading ASAR Package'
        if: success()
        uses: actions/upload-artifact@v1.0.0
        with:
          name: 'Time to Leave - Windows (Exe)'
          path: 'release-builds\Time to Leave-win32-ia32\Time to Leave.exe'
      - name: 'Creating Installer...'
        if: success()
        run: |
          npm run package:win-squirrel
          npx electron-installer-windows --src 'release-builds/time-to-leave-win32-ia32' --dest 'squirrel-release/time_to_leave.exe' --verbose

      - name: 'Uploading Installer...'
        if: success()
        uses: actions/upload-artifact@v1.0.0
        with:
          name: 'Time to Leave - Windows'
          path: 'squirrel-release/time_to_leave.exe'

env:
  CI: true
