name: Release on Tag
on:
  push:
    tags:
    - v.*
jobs:
  Building:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
    - name: Building App
      run: |
        npm ci --no-optional
        npm run package:mac
    - name: Uploading App
      uses: actions/upload-artifact@v1.0.0
      with:
        name: 'Time to Leave.app'
        path: 'release-builds/Time to Leave-darwin-x64/'
    - name: Creating DMG Package
      run: npx electron-installer-dmg 'release-builds/Time to Leave-darwin-x64/Time to Leave.app/' time-to-leave --out 'release-dmg' --icon=assets/icon-mac.icns
    - name: Uploading DMG Package
      uses: actions/upload-artifact@v1.0.0
      with:
        name: 'Time to Leave.dmg'
        path: 'release-dmg/time-to-leave.dmg'
    - name: Pre-Release
      uses: marvinpinto/action-automatic-releases@v0.2.2
      with:
        repo_token: ${{ secrets.TTL_RELEASE_TOKEN }}
        draft: true
        prerelease: true 
        title: 'Time to Leave - MacOS'
        files: 'release-dmg/time-to-leave.dmg'
      env:
        CI: true
