name: Update missing translations

on:
  push:
    branches:
      - main

jobs:
  missing-translations:
    if: github.repository == 'TTLApp/time-to-leave'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    - name: Write missing translation to file
      run: |
        python scripts/check_languages.py -output missing.md -report_summary -report_key_mismatch -report_missing_translations
    - name: Update comment
      uses: peter-evans/create-or-update-comment@v4
      with:
        # Update the comment in issue 475
        # https://github.com/TTLApp/time-to-leave/issues/475#issuecomment-808787273
        comment-id: 808787273
        edit-mode: replace
        body-path: missing.md
        reactions: hooray
